version: '3.8'

services:
  nestjs-api:
    container_name: nestjs-api
    depends_on:
      - mysql-db
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - .:/src/app
    command: npm run start:dev
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - minimart-network

  mysql-db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Admin@123
      - MYSQL_DATABASE=minimart
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - minimart-network

volumes:
  mysql_data:

networks:
  minimart-network:
    driver: bridge